---
- hosts: gateway
  #roles: [consul]
  handlers:
  - name: reload firewall
    service: name=iptables-persistent state=restarted
  - name: restart networking
    service: name=networking state=restarted
  - name: restart polipo
    service: name=polipo state=restarted

  tasks:
  - name: backports repo
    apt_repository: >
      repo='deb http://http.debian.net/debian wheezy-backports main contrib non-free'
      state=present
      update_cache=yes

  - name: software
    apt: name={{ item }} state=installed
    with_items:
    - sudo
    - vim
    - iptables-persistent
    - isc-dhcp-server
    - polipo

  - name: services
    service: name=polipo state=started enabled=yes
    with_items:
    - iptables-persistent
    - polipo
    - isc-dhcp-server

  - name: polipo configuration
    notify: restart polipo
    template: >
      src=polipo_config
      dest=/etc/polipo/config

  - name: forward packets
    sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

  - name: firewall rules
    template: src=firewall_rules dest=/etc/iptables/rules.v4
    notify: reload firewall

  - name: use Google nameservers
    notify: restart networking
    lineinfile: >
      line="supersede domain-name-servers 8.8.8.8, 8.8.4.4;"
      regexp="^supersede"
      dest=/etc/dhcp/dhclient.conf
