---
- hosts: styx.home
  handlers:
    - name: restart udev
      sudo: yes
      service: name=udev state=restarted
    - name: aoe link
      sudo: yes
      command: /bin/ip {{ item }}
      with_items:
      - link set aoe up
      - link set dev aoe mtu 9000
    #- name: aoe link
    #  sudo: yes
    #  command: /bin/ip link set aoe up
    #- name: aoe jumbo frames
    #  sudo: yes
    #  command: /bin/ip link set dev aoe mtu 9000
    - name: start vblades
      sudo: yes
      command: /usr/sbin/vblade-persist auto 0 0
    - name: restart murmur
      sudo: yes
      service: name="mumble-server" state=restarted

  tasks:
    #- name: update packages
    #  sudo: yes
    #  apt: upgrade=safe
    - name: vim
      sudo: yes
      apt: name=vim state=latest

    - name: network names
      sudo: yes
      copy: src=files/etc_udev_rules_d_70_persistent_net_rules
            dest="/etc/udev/rules.d/70-persistent-net.rules"
      notify: [restart udev]

    - name: network setup
      sudo: yes
      copy: src=files/etc_network_interfaces
            dest=/etc/network/interfaces
      # seems to bring down access
      # notify: [restart network]

    - name: start aoe link
      sudo: yes
      lineinfile: line='{{ item }}'
                  dest=/etc/rc.local
                  state=present
                  insertbefore='^exit 0'
      with_items:
        - ip link set aoe up
        - ip link set dev aoe mtu 9000 
      notify: [aoe link]

    - name: aoe support
      sudo: yes
      apt: name={{ item }} state=latest
      with_items: [ vblade, vblade-persist ]
    - name: persist aoe exports
      sudo: yes
      command: /usr/sbin/vblade-persist setup 0 0 aoe /dev/md/storage creates=/var/lib/vblade-persist/vblades/e0.0
      notify: [start vblades]

    - name: murmur server
      sudo: yes
      apt: name="mumble-server" state=latest

    - name: enable bonjour in murmurd
      sudo: yes
      lineinfile: dest="/etc/mumble-server.ini"
                  regexp='bonjour='
                  line='bonjour=True'
      notify: restart murmur

    - name: start murmur server
      sudo: yes
      service: name="mumble-server" state=running enabled=true
      
