---
- name: restart consul
  service: name=consul state=restarted
- name: reload consul
  command: "{{ consul_home }}/bin/{{ consul_binary }} reload"
- name: reload eth0
  shell: "ifdown eth0; ifup eth0"
- name: restart dnsmasq
  service: name=dnsmasq state=restarted
